// <auto-generated />
namespace GiftRegistry.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class init_wishlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_wishlist));
        
        string IMigrationMetadata.Id
        {
            get { return "202201250155422_init_wishlist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
